export const deckDifficulty: Record<string, { level: number; reason: string }> = {
  "squirreled-away": { level: 6, reason: "You'll need to track lots of small creatures and decide when to sacrifice them" },
  "animated-army": { level: 5, reason: "Turn your stuff into creatures and attack - simple and fun!" },
  "peace-offering": { level: 7, reason: "You'll need to decide who to help and when, reading the table constantly" },
  "family-matters": { level: 6, reason: "Lots of creatures with similar abilities that all work together" },
  "endless-punishment": { level: 7, reason: "Every opponent action triggers something - you'll be busy all game!" },
  "jump-scare": { level: 8, reason: "Play creatures face-down to keep opponents guessing what they are" },
  "miracle-worker": { level: 6, reason: "You need to set up the top of your deck to cast spells at the perfect moment" },
  "death-toll": { level: 7, reason: "Lots of math with life totals and many things happening at once" },
  "revival-trance": { level: 6, reason: "You bring dead creatures back to life, but need to carefully manage your resources" },
  "limit-break": { level: 8, reason: "Lots of big decisions about how much mana to spend on each spell" },
  "counter-blitz": { level: 9, reason: "You'll need to make instant decisions on every single turn, not just yours" },
  "scions-and-spellcraft": { level: 7, reason: "Making creature tokens while also casting lots of spells requires planning" },
  "quick-draw": { level: 5, reason: "Attack early, attack often, and don't let up - easy to understand and play" },
  "grand-larceny": { level: 8, reason: "You'll be playing with their cards, so you need to learn what they do too" },
  "desert-bloom": { level: 6, reason: "Focus on playing lands and they'll reward you with benefits" },
  "most-wanted": { level: 7, reason: "Your outlaws all do different things when they attack or enter play" },
  "science": { level: 7, reason: "Build up energy like a battery, then spend it on powerful effects" },
  "mutant-menace": { level: 6, reason: "All your mutants make each other stronger with counters - straightforward!" },
  "scrappy-survivors": { level: 5, reason: "Make lots of small creatures and overwhelm opponents with numbers" },
  "hail-caesar": { level: 7, reason: "Military tactics with complex combat - figuring out attacks takes thought" },
  "food-and-fellowship": { level: 5, reason: "Make food tokens, eat them for benefits - deliciously simple!" },
  "riders-of-rohan": { level: 6, reason: "Riding creatures into battle with some tricks to learn along the way" },
  "elven-council": { level: 7, reason: "You need to look ahead and plan several turns in advance" },
  "hosts-of-mordor": { level: 6, reason: "Create an army of tokens - simple and effective!" },
  "eldrazi-incursion": { level: 9, reason: "Colorless mana and weird abilities make this confusing for new players" },
  "creative-energy": { level: 8, reason: "Lots of different card types working together creates complex situations" },
  "graveyard-overdrive": { level: 7, reason: "Bring back dead creatures repeatedly, but managing resources is tricky" },
  "tricky-terrain": { level: 8, reason: "Lands do way more than normal and create lots of triggers to track" },
  "forces-of-the-imperium": { level: 7, reason: "Military strategy with lots of creatures entering as teams" },
  "the-ruinous-powers": { level: 8, reason: "Things happen randomly - you won't always know what's coming, but neither will they!" },
  "tyranid-swarm": { level: 6, reason: "Create tons of creatures and overwhelm - simple swarm tactics!" },
  "necron-dynasties": { level: 7, reason: "Robot creatures that keep coming back from the dead" },
  "timey-wimey": { level: 9, reason: "Time travel mechanics are super confusing - lots of waiting and tracking" },
  "blast-from-the-past": { level: 7, reason: "Cards cast themselves from exile creating complicated timing puzzles" },
  "vampiric-bloodline": { level: 6, reason: "Vampires drink blood tokens for power - gothic and straightforward!" },
  "draconic-rage": { level: 5, reason: "Summon huge dragons and smash your opponents - simple and powerful!" },
  "spirit-squadron": { level: 6, reason: "Flying spirits that synergize together nicely" },
  "undead-unleashed": { level: 5, reason: "Zombies keep coming back from the dead - resilient and easy to play!" },
  "lorehold-legacies": { level: 7, reason: "Cast lots of instant and sorcery cards in one turn for explosive plays" },
  "symbiotic-swarm": { level: 7, reason: "Different creatures get different abilities - tracking them all is complex" },
  "arcane-maelstrom": { level: 9, reason: "Copying spells creates incredibly complicated situations" },
  "ruthless-regiment": { level: 6, reason: "All your humans make each other stronger - tribal synergy at its finest!" },
  "sliver-swarm": { level: 8, reason: "Every sliver changes ALL slivers - tracking all the abilities gets overwhelming" },
  "planeswalker-party": { level: 8, reason: "Multiple powerful allies with different abilities to manage each turn" },
  "blame-game": { level: 7, reason: "Force opponents to attack each other while staying safe yourself" },
  "revenant-recon": { level: 6, reason: "Sneaky rogues that reward you when they connect with opponents" },
  "deadly-disguise": { level: 7, reason: "Face-down creatures with hidden abilities take getting used to" },
  "deep-clue-sea": { level: 6, reason: "Collect clues like a detective, deciding when's the right time to solve them" },
  "eternal-might": { level: 5, reason: "Play big creatures and make them even bigger - smash and win!" },
  "living-energy": { level: 6, reason: "Build up energy counters with creatures, then unleash powerful effects" },
  "aura-of-courage": { level: 7, reason: "Enchantments on creatures are powerful but risky - lose the creature, lose everything" },
  "prosper-tome-bound": { level: 8, reason: "Playing cards from exile instead of your hand feels weird at first" },
  "reap-the-tides": { level: 6, reason: "Play lands, get rewards - easy to track and satisfying!" },
};
