export const deckDifficulty: Record<string, { level: number; reason: string }> = {
  "squirreled-away": { level: 6, reason: "Requires managing tokens and sacrifice triggers" },
  "animated-army": { level: 5, reason: "Straightforward 'turn artifacts into creatures' strategy" },
  "peace-offering": { level: 7, reason: "Political deck with complex decision-making and table management" },
  "family-matters": { level: 6, reason: "Multiple tribal synergies to track and optimize" },
  "endless-punishment": { level: 7, reason: "Many triggered abilities that punish opponents constantly" },
  "jump-scare": { level: 8, reason: "Requires tracking multiple face-down creatures and morph triggers" },
  "miracle-worker": { level: 6, reason: "Timing miracles and top-deck manipulation takes practice" },
  "death-toll": { level: 7, reason: "Complex life manipulation and trigger stacking" },
  "revival-trance": { level: 6, reason: "Graveyard recursion with multiple moving parts" },
  "limit-break": { level: 8, reason: "Complex X-spell calculations and mana management" },
  "counter-blitz": { level: 9, reason: "Highly reactive with instant-speed decisions every turn" },
  "scions-and-spellcraft": { level: 7, reason: "Token generation mixed with spell-slinging requires planning" },
  "quick-draw": { level: 5, reason: "Simple aggressive strategy with clear gameplan" },
  "grand-larceny": { level: 8, reason: "Stealing opponents' cards requires knowing their decks too" },
  "desert-bloom": { level: 6, reason: "Land-based strategy with multiple synergies to track" },
  "most-wanted": { level: 7, reason: "Outlaw tribal with various triggered abilities" },
  "science": { level: 7, reason: "Energy counter management and artifact synergies" },
  "mutant-menace": { level: 6, reason: "Straightforward mutant tribal with +1/+1 counters" },
  "scrappy-survivors": { level: 5, reason: "Simple go-wide strategy with junk tokens" },
  "hail-caesar": { level: 7, reason: "Military-style strategy with complex combat math" },
  "food-and-fellowship": { level: 5, reason: "Food tokens are easy to understand and use" },
  "riders-of-rohan": { level: 6, reason: "Mount mechanics and combat tricks to master" },
  "elven-council": { level: 7, reason: "Scrying and card selection requires planning ahead" },
  "hosts-of-mordor": { level: 6, reason: "Army token strategy is straightforward" },
  "eldrazi-incursion": { level: 9, reason: "Colorless mana and devoid mechanics are confusing" },
  "creative-energy": { level: 8, reason: "Artifact combos and multiple permanent types to juggle" },
  "graveyard-overdrive": { level: 7, reason: "Graveyard recursion with mana management" },
  "tricky-terrain": { level: 8, reason: "Complex land interactions and multiple triggers" },
  "forces-of-the-imperium": { level: 7, reason: "Squad mechanic and military strategy requires planning" },
  "the-ruinous-powers": { level: 8, reason: "Chaos-themed with unpredictable effects" },
  "tyranid-swarm": { level: 6, reason: "Straightforward swarm strategy with tokens" },
  "necron-dynasties": { level: 7, reason: "Artifact creatures with graveyard recursion" },
  "timey-wimey": { level: 9, reason: "Time counters and suspend are notoriously complex" },
  "blast-from-the-past": { level: 7, reason: "Suspend and cascade create complicated stack interactions" },
  "vampiric-bloodline": { level: 6, reason: "Blood tokens and vampire tribal are intuitive" },
  "draconic-rage": { level: 5, reason: "Smash face with dragons - simple and effective" },
  "spirit-squadron": { level: 6, reason: "Flying tribal with some spirit synergies" },
  "undead-unleashed": { level: 5, reason: "Zombie tribal is straightforward and resilient" },
  "lorehold-legacies": { level: 7, reason: "Spell-based strategy with graveyard recursion" },
  "symbiotic-swarm": { level: 7, reason: "Keyword counter management across many creatures" },
  "arcane-maelstrom": { level: 9, reason: "Copying spells creates extremely complex board states" },
  "ruthless-regiment": { level: 6, reason: "Human tribal with straightforward synergies" },
  "sliver-swarm": { level: 8, reason: "Every sliver changes all slivers - tracking abilities is tough" },
  "planeswalker-party": { level: 8, reason: "Multiple planeswalkers with different abilities to track" },
  "blame-game": { level: 7, reason: "Goad and forcing attacks requires political savvy" },
  "revenant-recon": { level: 6, reason: "Rogue tribal with straightforward attack triggers" },
  "deadly-disguise": { level: 7, reason: "Cloak and disguise mechanics take getting used to" },
  "deep-clue-sea": { level: 6, reason: "Clue tokens are simple but optimizing when to crack them matters" },
  "eternal-might": { level: 5, reason: "Big creatures with simple +1/+1 counter strategy" },
  "living-energy": { level: 6, reason: "Energy counters with creature synergies" },
  "aura-of-courage": { level: 7, reason: "Auras require protecting your creatures carefully" },
  "prosper-tome-bound": { level: 8, reason: "Exile-based gameplay with impulse draw is unintuitive" },
  "reap-the-tides": { level: 6, reason: "Landfall triggers are easy to track" },
};
